apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-generator-config
data:
  # Database basic configurations
  POSTGRES_DB: "cv_generator_db"
  POSTGRES_USER: "admin"
  
  # Backend environmental variables
  NODE_ENV: "production"
  PORT: "8080"
  BACKEND_URL: "http://192.168.49.2:30080"
  OPENAI_MODEL: "openai/gpt-4o-mini"
  OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
  SUPABASE_URL: "https://xpcjffjiuvtkmmjgwjlw.supabase.co"
  FRONTEND_URL: "http://192.168.49.2:30000"
  
  # Frontend environmental variables
  NEXT_PUBLIC_SUPABASE_URL: "https://xpcjffjiuvtkmmjgwjlw.supabase.co"
  NEXT_PUBLIC_API_URL: "http://192.168.49.2:30080/api" # Use Ingress URL here in production
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "345502140796-k2m6pbfp1153lrrr36q6c1klah5p8bcm.apps.googleusercontent.com"
